# Generated by Django 4.2.8 on 2023-12-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_user',
        ),
    ]
