[metadata]
name = django-polls
version = 0.1
description = A Django app for conducting polls and analyzing voting statistics.
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/vichnya/Django-Polls-Statistics-API
author = Victoria Chernysheva
license = BSD-3-Clause
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 4.2
    Intended Audience :: Developers
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find:
python_requires = >=3.8
install_requires =
    Django >= 4.2